services:
  image-vector-search:
    build:
      context: .
    container_name: image-vector-search
    ports:
      - "9866:8000"
    environment:
      IMAGE_SEARCH_EMBEDDING_PROVIDER: ${IMAGE_SEARCH_EMBEDDING_PROVIDER:-jina}
      IMAGE_SEARCH_IMAGES_ROOT: /data/images
      IMAGE_SEARCH_INDEX_ROOT: /data/config
    volumes:
      - ./data/config:/data/config
      - ./data/images:/data/images:ro
